name: Mirror Rootfs Cache
on:
  workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:

  release-start:
    name: Prepare
    runs-on: [ubuntu-latest]

    steps:

      - name: Get
        shell: bash      
        run: |
        
          gh release download --pattern 'amd64-bullseye-cinnamon-4ad451f6-0116.tar.zst' -R https://github.com/armbian/cache
          gh release upload 0116 'amd64-bullseye-cinnamon-4ad451f6-0116.tar.zst' -R https://github.com/armbianworker/cache --clobber
