name: Mirror Rootfs Cache
on:
  workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:

  release-start:
    name: Prepare
    runs-on: [ubuntu-latest]

    steps:

      - name: Get
        shell: bash
        run: |
        
          gh release download 0116 --clobber --pattern 'amd64-bullseye-cinnamon-4ad451f6-0116.tar.zst.asc' -R https://github.com/armbian/cache 

      - name: Send
        shell: bash
        run: |

          gh release view 0116 --repo github.com/armbian/cache || gh release create 0116 -R https://github.com/armbianworker/cache
          gh release upload 0116 'amd64-bullseye-cinnamon-4ad451f6-0116.tar.zst.asc' -R https://github.com/armbianworker/cache --clobber
