name: Mirror Rootfs Cache
on:
  workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:

  release-start:
    name: Prepare
    runs-on: [ubuntu-latest]

    steps:

      - name: Get
        shell: bash
        run: |
        
          mkdir -p json
          sudo npm install --location=global json || true
          gh release view 0116 --repo github.com/armbianworker/cache || gh release create 0116 -R https://github.com/armbianworker/cache
        
          gh release view --json assets --repo github.com/armbian/cache 2>/dev/null | python3 -mjson.tool | sed '1,2d;$d' | json -ga name | (while read -r line; do
          echo "Check if $line exists"
          if [[ -z $(gh release view 0116 --repo github.com/armbianworker/cache | grep $line) ]]; then
              echo "Download"
              gh release download 0116 --clobber --pattern $line -R https://github.com/armbian/cache
              echo "Upload"
              gh release upload 0116 $line -R https://github.com/armbianworker/cache --clobber
              rm $line || true
          fi
          sleep 3
          
          done)
